[build]
  # Simple build command that prepares our server file
  command = "npm run build && npm run db:push"
  publish = "dist"
  ignore_warnings = true

[functions]
  directory = "dist"

# Force Node.js 18.x for compatibility
[build.environment]
  NODE_VERSION = "18"
  # Explicitly disable Next.js plugin
  NETLIFY_NEXT_PLUGIN_SKIP = "true"

# Two simple redirects
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/server/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200