[build]
  command = "npm run build && mkdir -p dist/functions && cp server/functions/server.cjs dist/functions/server.js && cp server/functions/vite.cjs dist/functions/vite.cjs && echo 'Build completed successfully'"
  publish = "dist/public"
  ignore_warnings = true

[functions]
  directory = "dist/functions"

# Force Node.js 18.x for compatibility
[build.environment]
  NODE_VERSION = "18"
  NETLIFY_USE_NEXTJS = "false"

[[redirects]]
  from = "/api/*" 
  to = "/.netlify/functions/server/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200