[build]
  command = "npm run build && cp -r server/functions dist/ && echo 'Build completed successfully'"
  publish = "dist/public"
  ignore_warnings = true

[functions]
  directory = "dist/functions"

# Force Node.js 18.x for compatibility
[build.environment]
  NODE_VERSION = "18"
  # Make sure Next.js plugin doesn't interfere with our Vite build
  NETLIFY_NEXT_PLUGIN_SKIP = "true"
  # Forcibly disable Next.js plugin completely
  NETLIFY_USE_NEXTJS = "false"

[[redirects]]
  from = "/api/*" 
  to = "/.netlify/functions/server/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200