[build]
  # Simple build command that prepares our server file
  command = "npm run build && mkdir -p dist/functions && cp server/functions/server.js dist/functions/ && npm install node-fetch@2 --no-save && echo 'Build completed successfully'"
  publish = "dist/public"
  ignore_warnings = true

[functions]
  directory = "dist/functions"

# Force Node.js 18.x for compatibility
[build.environment]
  NODE_VERSION = "18"
  # Explicitly disable Next.js plugin
  NETLIFY_NEXT_PLUGIN_SKIP = "true"

# Two simple redirects
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/server/api/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200